@startuml
!theme toy

title Test architecture design
skinparam linetype ortho

actor start
actor end
frame  {
    package ProcessD #aaa {
        control Thread2 as c2
        node logic as n3
    }
    package ProcessC #aaa {
        queue sumObject as q1
    }
    package ProcessB #aaa {
        control Thread as c1
        node logic as n2
    }
}
node IE as n1
frame layerDB {
    database setting as d1
    database billing as d2
}


start -> n1
n1 -> c1
c1 --> n2
    n2 <--> d1
c1 -> q1
q1 -> c2
c2 -> end
c2 --> n3
    n3 -> d2

@enduml