@startuml
!theme toy
skinparam linetype ortho

title Researchad architecture design


actor User
frame Media {
    node MediaSite
}
frame ResearchadService #aaa {
    component CoreLogic
    component Collector
    node ResearchadSite
    ResearchadSite <-> CoreLogic
}
frame Database {
    database 광고통계
    database 광고소재
}

User --> ResearchadSite : Report & AdInformation
CoreLogic <--> Database
Collector --> MediaSite : Clipping
Collector --> Database

@enduml